export const REGISTER_USER_REQUEST:string = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS:string = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE:string = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST:string = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS:string = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE:string = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_SUCCESS:string = "LOGOUT_USER_SUCCESS ";
export const SELECT_ACTIVE_CONTACT:string = "SELECT_ACTIVE_CONTACT";

export const CONTACTS_REQUEST:string = "CONTACTS_REQUEST";
//export const CONTACTS_SUCCESS:string = "CONTACTS_SUCCESS";
export const CONTACTS_FAILURE:string = "CONTACTS_FAILURE";

export const CREATE_CONTACT_REQUEST:string = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS:string = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAILURE:string = "CREATE_CONTACT_FAILURE";

export const DELETE_CONTACT_REQUEST:string = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS:string = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE:string = "DELETE_CONTACT_REQUEST";

export const LOAD_CONTACTS_REQUEST:string = "LOAD_CONTACTS_REQUEST";
export const LOAD_CONTACTS_SUCCESS:string = "LOAD_CONTACTS_SUCCESS";